# Generated by Django 4.2 on 2023-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
