# Generated by Django 4.2 on 2023-04-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_member_firstname_remove_member_joined_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Tab',
        ),
    ]
