# Generated by Django 4.2 on 2023-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_member_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.CharField(max_length=100000, null=True)),
                ('tag', models.CharField(default='informacja', max_length=255)),
            ],
        ),
    ]
